services:
  - type: web
    name: tbiliso-oldenburg
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: TBILISO_CHEF_PW
        value:TbilisoChefZurab
      - key: TBILISO_SECRET
        generateValue: true
